from enum import StrEnum


class Drill(StrEnum):
    JUMP_LANDING = "JUMP_LANDING"
    SINGLE_LEG_SQUAT = "SINGLE_LEG_SQUAT"
    SPRINT_ACCELERATION = "SPRINT_ACCELERATION"
    CUTTING = "CUTTING"
    KICKING = "KICKING"


class CameraView(StrEnum):
    FRONTAL = "FRONTAL"
    LEFT_SAGITTAL = "LEFT_SAGITTAL"
    RIGHT_SAGITTAL = "RIGHT_SAGITTAL"
    SAGITTAL = "SAGITTAL"
    REAR = "REAR"
    MULTI_VIEW = "MULTI_VIEW"


class ScreeningStatus(StrEnum):
    VIDEO_PENDING = "VIDEO_PENDING"
    VIDEO_UPLOADED = "VIDEO_UPLOADED"
    QUEUED = "QUEUED"
    QUALITY_CHECKING = "QUALITY_CHECKING"
    RETAKE_REQUIRED = "RETAKE_REQUIRED"
    PROCESSING_POSE = "PROCESSING_POSE"
    PROCESSING_BIOMECHANICS = "PROCESSING_BIOMECHANICS"
    PROCESSING_RISK = "PROCESSING_RISK"
    PROCESSING_INTERPRETATION = "PROCESSING_INTERPRETATION"
    AI_COMPLETE = "AI_COMPLETE"
    AWAITING_CLINICIAN_REVIEW = "AWAITING_CLINICIAN_REVIEW"
    UNDER_CLINICAL_REVIEW = "UNDER_CLINICAL_REVIEW"
    CLINICIAN_REVIEWED = "CLINICIAN_REVIEWED"
    REFERRED_TO_PHYSIO = "REFERRED_TO_PHYSIO"
    PHYSIO_REVIEWED = "PHYSIO_REVIEWED"
    REPORT_READY = "REPORT_READY"
    FAILED = "FAILED"


class QualityStatus(StrEnum):
    ACCEPTABLE = "ACCEPTABLE"
    RETAKE_REQUIRED = "RETAKE_REQUIRED"


class RiskSignal(StrEnum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    ELEVATED = "ELEVATED"
    HIGH = "HIGH"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
